[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
